feat(Checkout): create transparent checkout
ecomplus/app-infinitepay pull request #80
Opened 2022-07-26 14:39 UTC by wisley7l

Relacionado ao issue #77

2022-07-26 18:15 UTC, leomp12 requested changes
Coé @wisley7l ,
Me ative à config do app por enquanto, acho que dá pra melhorar uns 🚃

2022-07-26 18:15 UTC, leomp12 commented on functions/ecom.config.js
> +          },
Isso é da conta do merchant, não tá diretamente relacionado à forma de pagamento, implementando Pix ele não deve ter que adicionar outras credenciais...

2022-07-26 18:15 UTC, leomp12 commented on functions/ecom.config.js
> +    },
Não acho que deveria adicionar esse objeto, acho que o objeto `gateway_options` (que já representa configurações pro link) deveria ser renomeado: https://github.com/ecomplus/app-infinitepay/blob/c812b3e9ec660f756b7befe5bf8551fda6cc78a9/functions/ecom.config.js#L282-L311 
Pode passar a ser `payment_link` e ter essa nova propriedade (booleano) `disable`

2022-07-26 18:15 UTC, leomp12 commented on functions/ecom.config.js
>      },
Aliás aqui também https://github.com/ecomplus/app-infinitepay/blob/c812b3e9ec660f756b7befe5bf8551fda6cc78a9/functions/routes/ecom/modules/create-transaction.js#L200-L204

2022-07-26 18:15 UTC, leomp12 commented on functions/ecom.config.js
> +      hide: false
Então quer dizer que você iria expor client ID e secret? 😄

2022-07-26 18:15 UTC, leomp12 commented on functions/ecom.config.js
> +      hide: false
> Aqui pode ser `hide: false` mesmo, negócio é que o ID e secret não deveriam estar dentro do objeto (público) de configuração de cartão de crédito

2022-07-27 15:36 UTC, wisley7l commented
Fiz aqui as correções, solicitadas ja alterando as requisições sem o `api_key`.

2022-07-27 20:51 UTC, leomp12 commented
Vamos ter que manter a API key (😞) mas usar só em transação com link de pagamento...

2022-07-27 21:13 UTC, leomp12 requested changes

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/list-payments.js
> -  if (!config.infinitepay_api_key) {
Se o link estiver ativo tem que checar API key né...

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/infinitepay/callback.js
> +                return axios.get(`/v1/transactions/${transactionId}`)
Você tem que usar v2 aqui, não?

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/infinitepay/callback.js
> +                return axios.get(`/v1/transactions/${transactionId}`)
```suggestion
                return axios.get(`/v2/transactions/${transactionId}`)
```

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/infinitepay/callback.js
> +                return axios.get(`/v1/transactions/${transactionId}`)
Pelo que entendi da conversa lá o JWT é só pra v2 da API deles..

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
>      })
Ou se pá mantém e testamos pra ver se funciona, vai que...

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
>      })
Na real eles não falaram com certeza

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +        return axios.post('/v2/transactions', data, { headers })
Tem que ter um timeout de uns 40s aqui, essa história de análise síncrona da transação não me parece bom 😛 
Se der timeout você segue mas deixa a transação com status `under_analysis`

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +          .catch(console.error)
Tá usando isso aqui pra quê? 🤔

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +    data.metadata.risk.payer_ip = payerIp
Pode colocar campos quaisquer no metadata, certo? (é o que se espera de _metadata_ 😄 )
Adiciona order ID, vai ser útil depois quando os webhooks funcionarem.
Adiciona order number também, vai ser útil pro lojista se os metadados aparecerem no pedido em algum lugar no app da InfinitePay.

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +          .catch(console.error)
Não tem dado do cartão aqui não né? 😄

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +          .catch(console.error)
De qualquer forma, acho que c não precisa de Firestore aqui não

2022-07-27 21:13 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +            current: 'authorized',
```suggestion
            current: 'paid',
```

Como não tem webhook, tem que entrar direto como pago...

2022-07-28 13:52 UTC, wisley7l commented on functions/routes/ecom/modules/create-transaction.js
> +        return axios.post('/v2/transactions', data, { headers })
Aqui eu boiei. ☹️
Pq aqui usamos a resposta dessa requisição para responder o create-transaction, pq pelo que entendi na doc dele é que essa requisição ou vai retornar o i`d da transação `ou `null`

2022-07-28 18:47 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +        return axios.post('/v2/transactions', data, { headers })
Então, é que a transação é analisada de forma síncrona e essa análise pode demorar em alguns casos (anti-fraude), pra evitar que a function só morra por timeout ou que o próprio checkout encerre a request (ele também tem um limite de tempo pra criação da transação) a gente tem que adicionar um timeout na request (opção do axios) de criação da transação, se passar desse limite de tempo você não vai ter o ID da transação mesmo, vai pro catch e você checa lá se deu timeout, nesse caso só resta responder sem ID da transação e com status `under_analysis`

2022-07-28 18:48 UTC, leomp12 commented on functions/routes/ecom/modules/create-transaction.js
> +        return axios.post('/v2/transactions', data, { headers })
O lojiste nesse caso teria que ver qual é a transação manualmente mesmo...

2022-07-29 21:28 UTC, leomp12 approved these changes
valeu nelson ! 👍🏾

2022-07-29 21:28 UTC, merged